### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by vfcp** [jophj/GoIntelligence#1]
Unable to see webapp due to below error. It seems to be related with gymTrackr.config reference. 

Uncaught Error: [$injector:modulerr] Failed to instantiate module gymTrackr due to:
Error: [$injector:modulerr] Failed to instantiate module gymTrackr.gymStatus due to:
Error: [$injector:modulerr] Failed to instantiate module gymTrackr.gymDetails due to:
Error: [$injector:modulerr] Failed to instantiate module gymTrackr.config due to:
Error: [$injector:nomod] Module 'gymTrackr.config' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.4/$injector/nomod?p0=gymTrackr.config
    at http://docker31327-pokeeyes.mircloud.host/libs.min.js:1:425
    at http://docker31327-pokeeyes.mircloud.host/libs.min.js:1:11705
    at n (http://docker31327-pokeeyes.mircloud.host/libs.min.js:1:11162)
    at http://docker31327-pokeeyes.mircloud.host/libs.min.js:1:11479
    at http://docker31327-pokeeyes.mircloud.host/libs.min.js:1:21384
    at o (http://docker31327-pokeeyes.mircloud.host/libs.min.js:1:1005)
    at m (http://docker31327-pokeeyes.mircloud.host/libs.min.js:1:21232)
    at http://docker31327-pokeeyes.mircloud.host/libs.min.js:1:21416
    at o (http://docker31327-pokeeyes.mircloud.host/libs.min.js:1:1005)
    at m (http://docker31327-pokeeyes.mircloud.host/libs.min.js:1:21232)

Thanks for your help!

**Comment by vfcp** [comment]
My bad. Forgot to edit app.config.js.example
